@startuml
'https://plantuml.com/sequence-diagram

class App{
}

class fileReader{
    - BufferedReader br
    + getList ArrayList<String>()
    + readFile void()
    + readFileLine String()
    + makeFileReader BufferedReader()
}

class nameFormatter{
    + splitString String[](String nameLine)
    + makeTable String(ArrayList<String> list)
}

App o-> fileReader
App o--> nameFormatter




@enduml