@startuml
'https://plantuml.com/sequence-diagram

class App{
    + askForName String()
    + askForAuthor String()
    + askJS boolean()
    + askCSS boolean()
}

class makeWebsite{
    + setFiles void()
    + makeDirectories void()
    + makeHTML String()
}

App o-> makeWebsite
@enduml